### ISSUE TITLE
test-suite Sources Not Installed

### ISSUE THREAD

**Issue by creichert** [tfausak/haskeleton#27]
It seems the test-suite sources are not installed (only the Example.ModuleSpec.hs).

```
$ hi     --moduleName 'Example.Module'     --repository 'https://github.com/tfausak/haskeleton.git'     --author 'Jane Doe'     --email 'jane.doe@example.com' example-module
Creating new project with git repository:https://github.com/tfausak/haskeleton.git
    create  example-module/LICENSE.md
    create  example-module/Makefile
    create  example-module/README.md
    create  example-module/benchmark/Bench.hs
    create  example-module/benchmark/Example/ModuleBench.hs
    create  example-module/executable/Main.hs
    create  example-module/haskeleton.hs
    create  example-module/library/Example/Module.hs
    create  example-module/example-module.cabal
    create  example-module/test-suite/Example/ModuleSpec.hs
```

I'm not too sure how module discovery works but when I manuall add a Spec.hs with `{-# #-}` then it complains that DocTest is not there

I quickly glanced through the source in an attempt to fix this with no luck. I'll be happy to provide a patch if you could point me in the right direction.

**Comment by tfausak** [comment]
Which version of hi are you using? Version 1.0.0 was recently released, but I have not tested it yet. Everything should work with version 0.0.8.x.

**Comment by creichert** [comment]
Ah, that makes sense. It's the newest version. I knew something was up after the first few issues but I had not used haskeleton or hi before. Some of my Pull Requests might not make sense but I wouldn't mind making them compatible with both versions.

**Comment by tfausak** [comment]
I would rather support only version 1 of hi instead of maintaining backwards compatibility for version 0.0.8.
