### ISSUE TITLE
Fix GHC 7.6 build

### ISSUE THREAD

**Issue by tfausak** [tfausak/haskeleton#30]
@creichert ran into this failure before:

> the build is failing due to `hi`'s dependency on `process`. If it uses callCommand it will need `process>=1.2`.

https://github.com/tfausak/haskeleton/pull/26#issuecomment-68745484

**Comment by creichert** [comment]
Awesome! thanks for all the fixes.

**Comment by tfausak** [comment]
This one can be fixed in `.travis.yml`, but it's really a problem with `hi`. I've created an issue: fujimura/hi#46.
