### ISSUE TITLE
Coverage suit FAIL on new project

### ISSUE THREAD

**Issue by drojas** [tfausak/haskeleton#31]
Context:

- OSX Yosemite 10.10.2
- Haskell Platform 2014.2.0.0

Output from `make test`

```
Test suite coverage: RUNNING...
	coverage: readProcess: hpc “report” “dist/hpc/tix/tests/tests.tix” (exit 1): failed
	Test suite coverage: FAIL
```

Content of `dist/hpc`

```
|-dist
   |---hpc
   |-----vanilla
   |-------tix
   |---------coverage
   |---------documentation
   |---------examples
   |---------style
   |---------tests
```

As you can see, there is a novel `vanilla` subdirectory and all leaf dirs are empty.

Also there exists a `tests.tix` file in the root of the project with the following content:
```hs
Tix [ TixModule "Zigurat" 2081514960 3 [6,6,6], TixModule "ZiguratSpec" 1408348398 11 [6,6,6,6,6,6,6,6,6,6,6], TixModule "Main" 3576103655 9 [6,6,6,6,6,6,6,6,6]]
```

Changing `test-suite/HPC.hs:12` from `, "dist/hpc/tix/tests/tests.tix"` to `, "tests.tix"` does not solves the problem.

**Comment by SantiMunin** [comment]
I've been able to get the .tix file in `dist/hpc/vanilla/tix/hspec/hspec.tix` being `hspec` the name of my suite.

Did you use `cabal configure --enable-tests --enable-coverage`? I am using Yosemite as well.

If I execute `cabal test hpc` after that I get another error though:

`hpc: can not find ApiSpec in ["./.hpc"]` (`.hpc` doesn't even exist in my directory)

(ApiSpec is not a test but a module, yeah I should change the name).

**Comment by tfausak** [comment]
Can y'all see if the changes I made in #32 fix this issue for you?

**Comment by SantiMunin** [comment]
It seems to work for me as well.
