### ISSUE TITLE
Is there a reason it is not using Tasty?

### ISSUE THREAD

**Issue by cies** [tfausak/haskeleton#33]
I think it makes a great case for inclusion in this project :)

**Comment by tfausak** [comment]
There is no reason. I think it would be nice to use [Tasty](http://hackage.haskell.org/package/tasty). I am more familiar with [Hspec](http://hackage.haskell.org/package/hspec), so that is what I used.

**Comment by cies** [comment]
It is not either tasty or hspec. It is tasty that enables hspec, hunit,
quickcheck, etc, to sit behind the same uniform (CLI) interface. Its a very
well done library, and very commonly used.

**Comment by tfausak** [comment]
I understand. Tasty has a bunch of providers for different test runners. 

One advantage to Hspec over tasty-hspec is auto discovery. That might not be a problem though, since I provide the `Haskeleton.hs` script for creating new modules.

**Comment by tfausak** [comment]
As noted in #34, getting Tasty to work is hard because of dependencies. I think I will only support it in the forthcoming Stack version of Haskeleton (#36).
