### ISSUE TITLE
Implement as a Stack template

### ISSUE THREAD

**Issue by tfausak** [tfausak/haskeleton#36]
I think that [Stack](https://github.com/commercialhaskell/stack) is the way forward for managing Haskell projects. I should change Haskeleton from a hi template to a Stack template.

**Comment by ibotty** [comment]
Please leave it an option. Some people don't like to use stack and prefer to continue using cabal.

**Comment by tfausak** [comment]
:+1: haskeleton-stack will probably be a separate project. 

Out of curiosity, why do you prefer Cabal over Stack?

**Comment by ibotty** [comment]
I prefer regular hackage (with the multitude of package versions) to stackage and did not find any compelling reason to switch to stack. I also prefer the non-monolithic nature of cabal and thus am looking for improvements in cabal and not in stack.

**Comment by tfausak** [comment]
Fair enough. You can use Stack without Stackage, but that's not the usual workflow. 

What do you mean when you say that Stack is monolithic?

**Comment by ibotty** [comment]
stack promotes working a way of developing that is monolithic. that's what i was trying to say.

**Comment by tfausak** [comment]
I agree that it encourages leaving out version bounds, and I agree that's a problem. I still don't understand what you mean by "monolithic", though.

**Comment by Pitometsu** [comment]
For this moment I use this with stack (incomplete a little yet)
```make
.PHONY: all benchmarks build clean configure coverage docs init install repl run test

jobs = 9

all: init configure build docs test coverage benchmarks

benchmarks:
	stack build --bench --jobs $(jobs) \
	&& $$(stack path --dist-dir)/build/benchmarks/benchmarks -o $$(stack path --project-root)/benchmarks.html \
	&& xdg-open $$(stack path --project-root)/benchmarks.html

build:
	stack build --jobs $(jobs)

clean:
	stack clean
	if test -f stack.yaml; then rm -r stack.yaml; fi
	if test -d .hpc; then rm -r .hpc; fi
	if test -f benchmarks.html; then rm -r benchmarks.html; fi

configure:
	cabal configure --enable-benchmarks --enable-tests --enable-coverage --enable-profiling --package-db=clear --package-db=global --package-db=$$(stack path --snapshot-pkg-db) --package-db=$$(stack path --local-pkg-db)
#  --builddir=$$(stack path --dist-dir)

coverage:
	stack exec -- hpc report --hpcdir=$$(stack path --dist-dir)/hpc/.hpc --per-module $$(find . -name tests.tix)

docs:
	stack haddock --no-haddock-deps \
	&& xdg-open $$(stack path --local-doc-root)/ConcatCheck-0.0.1/index.html

init:
	stack init --force --resolver lts-3.4
	stack solver --modify-stack-yaml

install:
	stack install

profile:
	stack build --library-profiling --executable-profiling --jobs $(jobs)

repl:
	stack ghci --jobs $(jobs)

run:
	stack exec ConcatCheck --jobs $(jobs)

test:
	stack build --test --coverage --jobs $(jobs)
# --coverage --ghc-options "--exclude=tests --exclude=examples --exclude=coverage --exclude=documentation --exclude=style --exclude=benchmarks"
```

**Comment by tfausak** [comment]
Now that commercialhaskell/stack#1095 has landed, I can start working on this. That being said, I think Haskeleton for Stack should be available in [the stack-templates repository](https://github.com/commercialhaskell/stack-templates). So this issue pretty much covers commercialhaskell/stack#1153. 

Also, for what it's worth, I want to stop using `make`. `stack` makes all these commands a lot easier, and `make` is hard to use on Windows.

**Comment by tfausak** [comment]
Will hopefully be fixed by https://github.com/commercialhaskell/stack-templates/pull/30.

**Comment by Pitometsu** [comment]
@tfausak and how it should be use now via `stack`? How create project, add files to project with that template? Just use plain `stack` as is?

**Comment by tfausak** [comment]
My pull request hasn't been merged yet. Once it has, you can make a new project with:

``` sh
stack new your-project haskeleton -p github-username=your-username -p 'author-name=Your Name'
```

I decided to ditch `Haskeleton.hs`, which was responsible for creating new files in projects.

**Comment by Pitometsu** [comment]
@tfausak thanks for detailed answer. Probably it should be described somewhere in documentation...
And which tool you see as proper solution for add new files to project? Manually, [shake](http://shakebuild.com/), make?

**Comment by tfausak** [comment]
I got rid of `Haskeleton.hs` because I didn't use. Instead I manually added new files to my projects. I don't think you need a tool to do that. 

I will update this project's documentation when my Stack template pull request is merged.

**Comment by Pitometsu** [comment]
@tfausak thank you a lot for nice templates.

**Comment by bitemyapp** [comment]
I use Makefiles a lot like @Pitometsu's - I'd love it if we could make something like that standard for the templates.

**Comment by tfausak** [comment]
I don't use Make. My shell does a good enough job keeping track of my history that I find it unnecessary. But I'm open to adding it to the new version of Haskeleton. Just submit a pull request to [`haskeleton.hsfiles`](https://github.com/commercialhaskell/stack-templates/blob/336d2fce25e904b61b21f8960f0955aef7aab55f/haskeleton.hsfiles).
