### ISSUE TITLE
'Warning: Parse error: pattern' in tests

### ISSUE THREAD

**Issue by Moredread** [tfausak/haskeleton#37]
Hi,

I created a new package with 'hi' and the haskeleton template, but without modifying anything, the style test for the HPC and Haddock tests fails.

```
Test suite style: RUNNING...
test-suite/HPC.hs:27:59: Warning: Parse error: pattern
Found:
    match :: String -> [Int]
  > match = fmap read . concat . catMaybes . fmap (matchRegex pattern) . lines
      where
        pattern = mkRegex "^ *([0-9]*)% "

test-suite/Haddock.hs:28:59: Warning: Parse error: pattern
Found:
    match :: String -> [Int]
  > match = fmap read . concat . catMaybes . fmap (matchRegex pattern) . lines
      where
        pattern = mkRegex "^ *([0-9]*)% "

2 suggestions
Test suite style: FAIL
```

I'm really new to Haskell, so I'm not sure what causes this. When I change 'patterns' to another variable name it passes.

**Comment by tfausak** [comment]
Thanks for reporting this! This is definitely a problem with Haskeleton. I re-ran the last successful build and [it failed](https://travis-ci.org/tfausak/haskeleton/jobs/62401999#L585), so this must be a problem with a new version of a dependency.

**Comment by tfausak** [comment]
I think this is happening because `pattern` is a keyword if you have the [`PatternSynonyms`](https://ghc.haskell.org/trac/ghc/wiki/PatternSynonyms) extension enabled. That extension is not enabled, but haskell-src-exts is parsing the file as if it was.

**Comment by tfausak** [comment]
This behavior was added to haskell-src-exts in version 0.17.0: https://github.com/haskell-suite/haskell-src-exts/blob/1.17.0/CHANGELOG#L42
